Playlist Maker - Добавлено воспроизведение музыку, автоматический пои…
Usynin1994/PlaylistMaker pull request #8
Opened 2023-05-03 16:35 UTC by Usynin1994

2023-05-04 17:42 UTC, kirillNay requested changes

2023-05-04 17:42 UTC, kirillNay commented on app/src/main/java/com/example/playlistmaker/PlayerActivity.kt
> +        private const val DELAY = 500L
⏫ В названии константных переменных, лучше указывать название величины. В данном случае `DELAY_MS`

2023-05-04 17:42 UTC, kirillNay commented on app/src/main/java/com/example/playlistmaker/PlayerActivity.kt
> +        mainThreadHandler = Handler(Looper.getMainLooper())
⏫ Нет необходимости делать `mainThreadHandler` `lateinit` и создавать его только в `onCreate`. `Looper.getMainLooper()` нам доступен в любом месте приложения и не привязан к жизненному циклу `Activity`

2023-05-04 17:42 UTC, kirillNay commented on app/src/main/java/com/example/playlistmaker/PlayerActivity.kt
> +        play = playerBinding.playButton
⏫ Так как мы используем `viewBinding` а не `findViewById` у нас больше нет необходимости отдельно хранить переменную с ссылкой на `View`, мы ее можем получить сразу из `playerBinding.playButton`. 

Но если обращение `playerBinding.playButton` кажется сильно длинным можно оставить переменную play, но объявить ее следующим образом:
```
private val play: ImageView get() = playerBinding.playButton
```

Такого рода конструкция будет вызывать `playerBinding.playButton` каждый раз, когда мы обращаемся к переменной` play`. Таким образом мы избавляемся от необходимости обязательно проинициализировать переменную `play`

(лучше стараться везде, где это возможно избавляться от `lateinit`, это зло, да еще и не подсвечиваемое)

2023-05-04 17:42 UTC, kirillNay commented on app/src/main/java/com/example/playlistmaker/PlayerActivity.kt
> +    private lateinit var mainThreadHandler: Handler
⏫ Кажется, дважды создал `handler`

2023-05-04 17:42 UTC, kirillNay commented on app/src/main/java/com/example/playlistmaker/PlayerActivity.kt
> +    private fun startTimer () : Runnable {
⚠️ При каждом обращении к методу `startTimer()` создается новый экземпляр интерфейса `Runnable`. 
В таком случае, если ты передашь в handler колбек через вызов `handler.post(startTimer())`, а затем попытаешься его удалить через `handler.removeCallbacks(startTimer())`, он не удалится, т.к. новый объект, созданный в `startTimer` не будет найден в `handler`'е

2023-05-04 17:42 UTC, NoDopezzz commented on app/src/main/java/com/example/playlistmaker/PlayerActivity.kt
> +                    "mm:ss",
⏫ Логика форматирования времени под формат `mm:ss` в приложении используется несколько раз. Предлагаю выделить ее в отдельную функцию внутри какого-нибудь `object DateUtils`, чтобы избавиться от повторений кода.

2023-05-04 17:42 UTC, kirillNay commented on app/src/main/java/com/example/playlistmaker/PlayerActivity.kt
> +    private fun startTimer () : Runnable {
Советую сделать `Runnable` с реализацией таймера переменной, как было сделано в `SearchActivity` с `searchRunnable`

2023-05-04 17:42 UTC, kirillNay commented on app/src/main/java/com/example/playlistmaker/TrackAdapter.kt
> +        set(newValue) {
👍 Отличная идея использовать `DiffUtils`!

2023-05-04 17:42 UTC, NoDopezzz commented on app/src/main/res/drawable-night/pause_button.png
⏫ Иконки стоит использовать не в формате PNG, а в качестве VectorAsset - андроидовского представления SVG.
- SVG - это векторный формат, который может быть масштабирован до любого размера без потери качества изображения. Это очень полезно для разработчиков приложений Android, которые работают на различных устройствах с разными размерами экранов.
- Поскольку SVG-файлы хранятся в виде XML-документов, они обычно занимают меньше места, чем растровые изображения. 
- Цвета в векторных изображениях также можно выносить в файл ресурсов. Так, можно организовать более гибкую дизайн-систему приложения.
Кроме того, это поможет экономить занимаемое ресурсами место, если нам нужно иметь иконки разных цветов для разных тем приложения. Ведь вместо того, чтобы создавать две иконки и класть в drawable и drawable-night, мы можем создать одну иконку в drawable, а файл ресурса с цветом будет задан в values и values-night

2023-05-05 00:34 UTC, Usynin1994 commented on app/src/main/java/com/example/playlistmaker/PlayerActivity.kt
> +        private const val DELAY = 500L
Поправил.

2023-05-05 00:35 UTC, Usynin1994 commented on app/src/main/java/com/example/playlistmaker/PlayerActivity.kt
> +        mainThreadHandler = Handler(Looper.getMainLooper())
Поправил.

2023-05-05 00:43 UTC, Usynin1994 commented on app/src/main/java/com/example/playlistmaker/PlayerActivity.kt
> +        play = playerBinding.playButton
Поправил.

2023-05-05 00:43 UTC, Usynin1994 commented on app/src/main/java/com/example/playlistmaker/PlayerActivity.kt
> +    private lateinit var mainThreadHandler: Handler
Поправил.

2023-05-05 00:46 UTC, Usynin1994 commented on app/src/main/java/com/example/playlistmaker/PlayerActivity.kt
> +    private fun startTimer () : Runnable {
Поправил.

2023-05-05 00:47 UTC, Usynin1994 commented on app/src/main/java/com/example/playlistmaker/TrackAdapter.kt
> +        set(newValue) {
Благодарю!

2023-05-05 18:13 UTC, Usynin1994 commented on app/src/main/java/com/example/playlistmaker/PlayerActivity.kt
> +                    "mm:ss",
Поправил.

2023-05-06 03:52 UTC, Usynin1994 commented on app/src/main/res/drawable-night/pause_button.png
Поправил.

2023-05-06 17:04 UTC, NoDopezzz approved these changes

2023-05-08 17:32 UTC, merged